version: '2'
services:
  orders-db:
    image: mongo:3.0.4
    restart: always
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"
  orders:
    image: arijmansour/pfe_orders_microservices:latest
    hostname: pfe_orders_microservices
    restart: always
    ports:
      - "8082:80"
